export const RecipeList = [
  {
    id: 1,
    title: "[쾌걸근육맨]-갈비찜덮밥",
    steps: [
      "돼지갈비는 뼈 부분을 제거 후 먹기 좋은 크기로 썰어 칼집을 낸다.(돼지갈비는 찬물에 1시간 이상 담궈 핏물을 제거)",
      "볼에 양념재료를 모두 넣고 섞는다.",
      "돼지갈비를 섞은 양념에 넣고 골고루 섞어 30분 이상 재운다.",
      "팬에 돼지갈비, 양념까지 모두 붓고 국물이 없을 때까지 조린다.",
      "그릇에 밥을 담고 구운 갈비, 실고추를 올려 완성한다.",
    ],
    ingredients: [
      { name: "돼지갈비", quantity: "500g" },
      { name: "밥", quantity: "적당량" },
      { name: "실고추", quantity: "약간" },
    ],
    seasonings: [
      { name: "간장", quantity: "3숟가락" },
      { name: "설탕", quantity: "1숟가락" },
      { name: "맛술", quantity: "1/2숟가락" },
      { name: "배음료", quantity: "1종이컵" },
      { name: "다진마늘", quantity: "1숟가락" },
      { name: "다진생강", quantity: "1/2숟가락" },
      { name: "후추", quantity: "약간" },
    ],
    youtube: "Mk2O71B8m-A",
    origin: "만개의 레시피",
  },
  {
    id: 2,
    title: "[하울의 움직이는 성]-하울 정식",
    steps: [
      "베이컨은 먹기 좋게 자른다.",
      "팬에 식용유를 두른 후 베이컨을 굽는다.",
      "한쪽에 달걀을 굽는다.",
      "소금, 후추로 간하여 완성한다.",
    ],
    ingredients: [
      { name: "달걀", quantity: "3개" },
      { name: "통 베이컨", quantity: "2줄" },
    ],
    seasonings: [
      { name: "소금", quantity: "약간" },
      { name: "후추", quantity: "약간" },
      { name: "식용유", quantity: "약간" },
    ],
    youtube: "di1KfHkJfVs",
    origin: "만개의 레시피",
  },
  {
    id: 3,
    title: "[요리왕 비룡]-황금 볶음밥",
    steps: [
      "달걀에 소금, 후추를 넣고 섞는다.",
      "달걀물에 밥을 넣고 잘 섞는다.(15분간 냉장고에 두기)",
      "팬에 식용유를 두르고 대파를 볶아 파기름을 만든다.(파는 쓰지 않는다)",
      "파기름에 밥을 넣고 골고루 볶은 후 참기름을 넣고 섞어 완성한다.",
    ],
    ingredients: [
      { name: "밥", quantity: "1공기" },
      { name: "달걀", quantity: "2개" },
      { name: "송송 썬 대파", quantity: "1/2대" },
    ],
    seasonings: [
      { name: "소금", quantity: "약간" },
      { name: "후추", quantity: "약간" },
      { name: "참기름", quantity: "약간" },
      { name: "식용유", quantity: "약간" },
    ],
    youtube: "nAO6M3tzrzQ",
    origin: "만개의 레시피",
  },
  {
    id: 4,
    title: "[텔레토비]-스마일 쿠키",
    steps: [
      "볼에 버터를 넣어 부드럽게 푼다.",
      "설탕을 넣고 섞다가 달걀, 소금을 넣고 섞는다.",
      "박력분을 체쳐 넣고 섞는다.",
      "반죽을 나눠 약간 남긴 후 한쪽에는 코코아파우더를 넣고 섞는다.",
      "오븐팬에 반죽을 동그랗게 만들어 놓는다.",
      "남겨둔 반죽으로 눈, 입을 만든다.",
      "180도에서 10분간 구워 완성한다.",
    ],
    ingredients: [
      { name: "박력분", quantity: "180g" },
      { name: "코코아파우더", quantity: "2숟가락" },
      { name: "달걀", quantity: "1개" },
      { name: "설탕", quantity: "50g" },
      { name: "버터", quantity: "50g" },
    ],
    seasonings: [{ name: "소금", quantity: "약간" }],
    youtube: "EbeztweJNlw",
    origin: "만개의 레시피",
  },
  {
    id: 5,
    title: "[심슨]-슈가글레이즈 도넛",
    steps: [
      "볼에 달걀, 설탕을 넣고 잘 풀어준다.",
      "포도씨유, 우유를 넣고 잘 섞는다.(포도씨유, 우유는 전자레인지에서 10초간 2번 돌려 사용)",
      "찹쌀가루, 박력쌀가루, 아몬드가루, 베이킹파우더를 체에 내려 고루 섞는다.",
      "도넛틀에 담아 170도 예열된 오븐에 20분간 구워 충분히 식힌다",
      "슈가글레이즈 재료를 고루 섞는다.(레몬즙 대신 물을 사용 가능)",
      "충분히 식혀진 도넛에 슈가글레이즈를 묻혀 완성한다.(스프링클을 뿌리면 더 좋음)",
    ],
    ingredients: [
      { name: "찹쌀가루", quantity: "80g" },
      { name: "박력쌀가루", quantity: "80g" },
      { name: "아몬드가루", quantity: "50g" },
      { name: "베이킹파우더", quantity: "1/4숟가락" },
      { name: "달걀", quantity: "3개" },
      { name: "설탕", quantity: "1종이컵" },
      { name: "우유", quantity: "4숟가락" },
      { name: "포도씨유", quantity: "6숟가락" },
    ],
    seasonings: [
      { name: "슈가파우더", quantity: "1종이컵" },
      { name: "레몬즙", quantity: "2숟가락" },
      { name: "식용색소", quantity: "약간" },
    ],
    youtube: "4BgE9K3cGt4",
    origin: "만개의 레시피",
  },
];
